# Generated by Django 5.0.6 on 2024-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
