# Generated by Django 5.0.6 on 2024-07-04 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pupil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='project.pupil')),
            ],
        ),
    ]
