# Generated by Django 5.0.6 on 2024-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='code',
            field=models.CharField(default='xxx', editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
