# Generated by Django 5.0.6 on 2024-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_exam_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default='asdasdoiad ajsod jasd ', max_length=1024),
            preserve_default=False,
        ),
    ]
