# Generated by Django 5.0.6 on 2024-07-05 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_exam_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='project.exam')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='project.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='PupilAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='project.answer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='project.test')),
            ],
        ),
    ]
