# Generated by Django 5.0.6 on 2024-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_pupilanswer_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupilanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
